package com.fffan911.galaxy_defense.Model.Purchasables;

public enum PurchasableType {
	//Enum Values
	COMPOSITE_REPLACEMENT, COMPOSITE_UPGRADE, WEAPON_REPLACEMENT,
	WEAPON_UPGRADE, WEAPON_EVOLUTION, SPECIAL_REPLACEMENT, SPECIAL_UPGRADE,
	SPECIAL_EVOLUTION, ACCESSORY, KEY_ITEM,;
}
